# Generated by Django 3.1.1 on 2021-11-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_auto_20211117_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_accomplished',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
