# Generated by Django 3.1.1 on 2021-11-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_profile_date_accomplished'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
